"""
Base interfaces for the Performance Calculation Layer.

This module defines the standard interfaces for strategies, variable management,
and core trading logic.

Author: Claude Code
Date: 2025-10-25
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass
from enum import Enum
import pandas as pd


class SignalType(Enum):
    """Trading signal types."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE = "CLOSE"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    timestamp: pd.Timestamp
    signal_type: SignalType
    confidence: float  # 0-1 scale
    reason: str
    price: float
    metadata: Dict[str, Any] = None

    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}


@dataclass
class Variable:
    """A variable managed by the variable management system."""
    name: str
    value: float
    timestamp: pd.Timestamp
    symbol: str
    indicator_type: str  # 'technical', 'fundamental', 'derived'
    unit: Optional[str] = None


class IStrategy(ABC):
    """
    Interface for all trading strategies.

    All strategies (technical, ML, hybrid) must implement this interface
    to work with the unified calculation engine.

    Typical usage:
        strategy = MovingAverageStrategy(fast_period=10, slow_period=20)
        strategy.initialize(data)
        signals = strategy.generate_signals(data)
    """

    @abstractmethod
    def initialize(self, historical_data: pd.DataFrame, **kwargs) -> None:
        """
        Initialize the strategy with historical data.

        Args:
            historical_data: Historical OHLCV data
            **kwargs: Strategy-specific parameters

        Raises:
            ValueError: If data is invalid or insufficient
        """
        pass

    @abstractmethod
    def generate_signals(self, current_data: pd.DataFrame) -> List[Signal]:
        """
        Generate trading signals based on current data.

        Args:
            current_data: Current OHLCV data (typically recent bars)

        Returns:
            List of Signal objects

        Example:
            >>> signals = strategy.generate_signals(recent_data)
            >>> for signal in signals:
            >>>     print(f"{signal.symbol}: {signal.signal_type}")
        """
        pass

    @abstractmethod
    def get_parameters(self) -> Dict[str, Any]:
        """Get current strategy parameters."""
        pass

    @abstractmethod
    def set_parameters(self, parameters: Dict[str, Any]) -> None:
        """Set strategy parameters for optimization."""
        pass

    @property
    @abstractmethod
    def strategy_name(self) -> str:
        """Strategy identifier."""
        pass

    @property
    @abstractmethod
    def supported_symbols(self) -> List[str]:
        """List of symbols this strategy supports."""
        pass


class IVariableManager(ABC):
    """
    Interface for variable management system.

    Manages all indicators, derived values, and variables used in calculations.
    Ensures consistency and eliminates duplicate calculations.
    """

    @abstractmethod
    def register_variable(
        self,
        name: str,
        calculation_func,
        refresh_frequency: str = "daily"
    ) -> None:
        """
        Register a new variable with its calculation function.

        Args:
            name: Variable identifier
            calculation_func: Function that calculates the variable
            refresh_frequency: How often to recalculate ('daily', 'intraday', etc.)
        """
        pass

    @abstractmethod
    def get_variable(self, symbol: str, variable_name: str) -> Variable:
        """
        Get a variable value for a symbol.

        Returns cached value if available, otherwise calculates.
        """
        pass

    @abstractmethod
    def cache_variable(self, variable: Variable) -> None:
        """Cache a calculated variable."""
        pass

    @abstractmethod
    def clear_cache(self, symbol: Optional[str] = None) -> None:
        """Clear variable cache."""
        pass


class IParameterManager(ABC):
    """
    Interface for parameter management system.

    Manages optimization parameters, thresholds, and configuration values.
    """

    @abstractmethod
    def get_parameter(self, param_name: str, default: Any = None) -> Any:
        """Get a parameter value."""
        pass

    @abstractmethod
    def set_parameter(self, param_name: str, value: Any) -> None:
        """Set a parameter value."""
        pass

    @abstractmethod
    def get_optimization_bounds(self, param_name: str) -> Tuple[float, float]:
        """Get min/max bounds for parameter optimization."""
        pass

    @abstractmethod
    def load_parameters_from_dict(self, params: Dict[str, Any]) -> None:
        """Load all parameters from a dictionary."""
        pass


class IExecutionEngine(ABC):
    """
    Interface for order execution engine.

    Handles signal-to-execution conversion, order management, and position tracking.
    """

    @abstractmethod
    def execute_signal(self, signal: Signal) -> Dict[str, Any]:
        """
        Execute a trading signal.

        Returns execution result with order ID, status, etc.
        """
        pass

    @abstractmethod
    def get_current_position(self, symbol: str) -> Dict[str, Any]:
        """Get current position for a symbol."""
        pass

    @abstractmethod
    def close_position(self, symbol: str) -> Dict[str, Any]:
        """Close an open position."""
        pass
